# Copyright (c) 2022-2025, LabSim Project Developers.
# All rights reserved.
seed: 42

models:
  policy:  # Gaussian policy network
    class: GaussianMixin
    clip_actions: false
    clip_log_std: true
    min_log_std: -20.0
    max_log_std: 2.0
    network:
      - name: actor
        input: OBSERVATIONS
        layers: [256, 256]
        activations: tanh
    output: ACTIONS

  critic_1:
    class: DeterministicMixin
    network:
      - name: critic_1
        input: OBSERVATIONS_ACTIONS
        layers: [256, 256]
        activations: relu
    output: ONE

  critic_2:
    class: DeterministicMixin
    network:
      - name: critic_2
        input: OBSERVATIONS_ACTIONS
        layers: [256, 256]
        activations: relu
    output: ONE

  target_critic_1:
    class: DeterministicMixin
    network:
      - name: target_critic_1
        input: OBSERVATIONS_ACTIONS
        layers: [256, 256]
        activations: relu
    output: ONE

  target_critic_2:
    class: DeterministicMixin
    network:
      - name: target_critic_2
        input: OBSERVATIONS_ACTIONS
        layers: [256, 256]
        activations: relu
    output: ONE

memory:
  class: RandomMemory
  memory_size: 10000

trainer:
  class: SequentialTrainer
  timesteps: 100000
  environment_info: log

agent:
  class: SAC
  gradient_steps: 1
  batch_size: 64
  discount_factor: 0.99
  polyak: 0.005
  actor_learning_rate: 3.0e-4
  critic_learning_rate: 3.0e-4
  learning_rate_scheduler: KLAdaptiveLR
  learning_rate_scheduler_kwargs: {}
  state_preprocessor: RunningStandardScaler
  state_preprocessor_kwargs: {}
  random_timesteps: 0
  learning_starts: 0
  grad_norm_clip: 0
  learn_entropy: true
  entropy_learning_rate: 1.0e-3
  initial_entropy_value: 0.2
  target_entropy: null
  rewards_shaper: null
  mixed_precision: false
  experiment:
    directory: "sac_runs"
    experiment_name: ""
    write_interval: auto
    checkpoint_interval: auto
    store_separately: false
    wandb: false
    wandb_kwargs: {}